### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by 2110riya**
Solution of HRDSEQ

### CODE REVIEW

**Comment by masterchef2209** [comment]
you have one extra screenshot from SC31 in this pull request, remove it so that i can merge your PR

**Comment by masterchef2209** [comment]
please resolve merge conflicts so that i can merge

**Comment by 2110riya** [comment]
I have deleted the file.

**Comment by masterchef2209** [comment]
it is ok, you just have to rename the screenshot file because another file already exists with same name, do that so i can merge your PR

**Comment by masterchef2209** [comment]
LGTM :+1:

**Pull request merged**
