### PR TITLE
Solution for painting boxes

### PR DESCRIPTION
**Pull request by arhum602**

### CODE REVIEW

**Comment by masterchef2209** [comment]
:+1:

**Comment by masterchef2209** [comment]
you have exactly identical solution like @meishansharma, i am leaving you this time if i find copied solution again i will give 50 points penalty to both

**Comment by meishansharma** [comment]
Sir i am only ishan sharma

**Comment by meishansharma** [comment]
Sir perhaps you have send me the email instead of arhum

**Pull request merged**
